# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphql/graphql.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='graphql/graphql.proto',
  package='dfuse.eosio.v1',
  syntax='proto3',
  serialized_options=_b('Z\tpbgraphql'),
  serialized_pb=_b('\n\x15graphql/graphql.proto\x12\x0e\x64\x66use.eosio.v1\x1a\x1cgoogle/protobuf/struct.proto\"[\n\x07Request\x12\r\n\x05query\x18\x01 \x01(\t\x12*\n\tvariables\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x15\n\roperationName\x18\x03 \x01(\t\"?\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12%\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x15.dfuse.eosio.v1.Error\"\xa2\x01\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x31\n\tlocations\x18\x02 \x03(\x0b\x32\x1e.dfuse.eosio.v1.SourceLocation\x12(\n\x04path\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.ListValue\x12+\n\nextensions\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\".\n\x0eSourceLocation\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x05\x32K\n\x07GraphQL\x12@\n\x07\x45xecute\x12\x17.dfuse.eosio.v1.Request\x1a\x18.dfuse.eosio.v1.Response\"\x00\x30\x01\x42\x0bZ\tpbgraphqlb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='dfuse.eosio.v1.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='dfuse.eosio.v1.Request.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variables', full_name='dfuse.eosio.v1.Request.variables', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operationName', full_name='dfuse.eosio.v1.Request.operationName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=162,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='dfuse.eosio.v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='dfuse.eosio.v1.Response.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='dfuse.eosio.v1.Response.errors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=227,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='dfuse.eosio.v1.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dfuse.eosio.v1.Error.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locations', full_name='dfuse.eosio.v1.Error.locations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='dfuse.eosio.v1.Error.path', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extensions', full_name='dfuse.eosio.v1.Error.extensions', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=392,
)


_SOURCELOCATION = _descriptor.Descriptor(
  name='SourceLocation',
  full_name='dfuse.eosio.v1.SourceLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='dfuse.eosio.v1.SourceLocation.line', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column', full_name='dfuse.eosio.v1.SourceLocation.column', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=440,
)

_REQUEST.fields_by_name['variables'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_RESPONSE.fields_by_name['errors'].message_type = _ERROR
_ERROR.fields_by_name['locations'].message_type = _SOURCELOCATION
_ERROR.fields_by_name['path'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_ERROR.fields_by_name['extensions'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['SourceLocation'] = _SOURCELOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'graphql.graphql_pb2'
  # @@protoc_insertion_point(class_scope:dfuse.eosio.v1.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'graphql.graphql_pb2'
  # @@protoc_insertion_point(class_scope:dfuse.eosio.v1.Response)
  ))
_sym_db.RegisterMessage(Response)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'graphql.graphql_pb2'
  # @@protoc_insertion_point(class_scope:dfuse.eosio.v1.Error)
  ))
_sym_db.RegisterMessage(Error)

SourceLocation = _reflection.GeneratedProtocolMessageType('SourceLocation', (_message.Message,), dict(
  DESCRIPTOR = _SOURCELOCATION,
  __module__ = 'graphql.graphql_pb2'
  # @@protoc_insertion_point(class_scope:dfuse.eosio.v1.SourceLocation)
  ))
_sym_db.RegisterMessage(SourceLocation)


DESCRIPTOR._options = None

_GRAPHQL = _descriptor.ServiceDescriptor(
  name='GraphQL',
  full_name='dfuse.eosio.v1.GraphQL',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=442,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='dfuse.eosio.v1.GraphQL.Execute',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRAPHQL)

DESCRIPTOR.services_by_name['GraphQL'] = _GRAPHQL

# @@protoc_insertion_point(module_scope)
